name: tests_wf
permissions:
    contents: read

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      test-numpy:
        required: false
        type: boolean
        default: true
      test-extras:
        required: false
        type: boolean
        default: false
      upload-coverage:
        required: false
        type: boolean
        default: false
    secrets:
        codecov_token:
            required: true

env:
  PYTEST_ARGS: ""

jobs:
  tests:
    runs-on: ${{ inputs.os }}-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Install BLAS on PyPy3.10
      if: startsWith(inputs.python-version, 'pypy')
      run: sudo apt install -y libopenblas-dev
    - name: Set env variables
      run: echo "PYTEST_ARGS=--cov-append --cov=pydicom" >> "$GITHUB_ENV"
    - name: Check-out code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      with:
        fetch-depth: 2
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c  # v6.0.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
        allow-prereleases: true

    - name: Install pydicom and tools  # not 'editable install'
      run: |
        python -m pip install .[dev]

    - name: Ensure the pydicom data cache is up to date
      run: |
        python -c "from pydicom.data.data_manager import fetch_data_files; fetch_data_files()"

    - name: Test without numpy or handlers, incl pydicom-data (in [dev])
      run: |
        python -m pytest --cov-reset ${{ env.PYTEST_ARGS }}

    - name: Test with Numpy
      if: inputs.test-numpy
      run: |
        python -m pip install .[basic]
        python -m pytest ${{ env.PYTEST_ARGS }}

    - name: Test with all optional dependencies
      if: inputs.test-extras
      run: |
        python -m pip install .[pixeldata,gpl-license]
        python -m pytest ${{ env.PYTEST_ARGS }} tests/test_pylibjpeg.py
        python -m pytest ${{ env.PYTEST_ARGS }} tests/test_pillow_pixel_data.py
        python -m pytest ${{ env.PYTEST_ARGS }} tests/test_JPEG_LS_transfer_syntax.py tests/test_jpeg_ls_pixel_data.py
        python -m pytest ${{ env.PYTEST_ARGS }} tests/test_gdcm_pixel_data.py tests/pixels/test_encoder_gdcm.py
        python -m pytest ${{ env.PYTEST_ARGS }} tests/pixels

    - name: Test with missing libs
      if: inputs.test-extras
      # A small number of tests only run if libs missing
      run: |
        python -m pip uninstall -y pydicom_data pylibjpeg-openjpeg pylibjpeg-libjpeg pylibjpeg-rle
        python -m pytest ${{ env.PYTEST_ARGS }} tests/test_pylibjpeg.py tests/test_data_manager.py

    - name: Send coverage results
      if: success() && inputs.upload-coverage
      uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7  # v5.5.1
      with:
        token: ${{ secrets.codecov_token }}
        env_vars: inputs.os,inputs.python-version
